name: XinbotPlugin
main: xin.bbtt.mcbot.XinbotPlugin
version: 1.0.0
type: META_PLUGIN
commands:
  say:
    description: Say a message to the server
    usage: say <message>
  command:
    description: Execute a command on the server
    usage: command <command>
    aliases: [cmd]
  stop:
    description: Stop the bot
    usage: stop
  help:
    description: Show help
    usage: help [command]
    aliases: [?]
  disconnect:
    description: Disconnect the bot from the server
    usage: disconnect
    aliases: [dc]
  list:
    description: List online players
    usage: list
  pluginmanager:
    description: Manage plugins
    usage: pluginmanager
    aliases: [pm]
  plugins:
    description: List plugins
    usage: plugins
    aliases: [pl]
  license:
    description: Show license
    usage: license
