# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          # 让 setup-java 生成 settings.xml，并使用 GitHub Packages 的凭据
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN
          settings-path: ${{ github.workspace }}
          cache: maven

      - name: Build with Maven
        run: mvn -B -ntp clean package

      - name: Publish to GitHub Packages (Maven)
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -B -ntp deploy -s "$GITHUB_WORKSPACE/settings.xml"

      - name: Upload built artifacts (optional)
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: maven-artifacts
          path: |
            **/target/*.jar
            **/target/*.pom
