name: Dev Build on Push (Maven)

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  dev-build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: maven
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN
          settings-path: ${{ github.workspace }}

      - name: Build & Test
        run: mvn -B -ntp verify

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dev-${{ github.ref_name }}-${{ github.sha }}
          path: |
            target/*.jar
            target/*.zip
          if-no-files-found: warn

      - name: Deploy SNAPSHOT to GitHub Packages
        run: mvn -B -ntp -DskipTests deploy -s $GITHUB_WORKSPACE/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create pre-release (optional)
        if: ${{ false }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: dev-${{ github.ref_name }}-${{ github.sha }}
          name: "Dev build ${{ github.ref_name }} @ ${{ github.sha }}"
          prerelease: true
          files: |
            target/*.jar
            target/*.zip
